/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class NoAgent_detect */

#ifndef _Included_NoAgent_detect
#define _Included_NoAgent_detect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NoAgent_detect
 * Method:    caloffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NoAgent_detect_caloffset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
